[env:display_only241]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_INCLUDE_SIMPLE
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=16384

lib_deps =
    lvgl/lvgl@8.3.11
    hideakitai/ArxTypeTraits

monitor_speed = 115200
upload_speed = 921600
