[env:display_only191]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_INCLUDE_SIMPLE

lib_deps =
    lvgl/lvgl@8.3.11
    igorantolic/Ai Esp32 Rotary Encoder@^1.4
    hideakitai/ArxTypeTraits

monitor_speed = 115200
upload_speed = 921600
